<span style="color: blue; font-size: 30px">Import Libraries</span>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import folium

<span style="color: blue; font-size: 30px">Load the Dataset</span>

In [12]:
data = pd.read_csv("fordgobike.csv")
data.head(10)

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,member_birth_year,member_gender,bike_share_for_all_trip
0,52185,2019-02-28 17:32:10.1450,2019-03-01 08:01:55.9750,21.0,Montgomery St BART Station (Market St at 2nd St),37.789625,-122.400811,13.0,Commercial St at Montgomery St,37.794231,-122.402923,4902,Customer,1984.0,Male,No
1,42521,2019-02-28 18:53:21.7890,2019-03-01 06:42:03.0560,23.0,The Embarcadero at Steuart St,37.791464,-122.391034,81.0,Berry St at 4th St,37.775880,-122.393170,2535,Customer,NaN,NaN,No
2,61854,2019-02-28 12:13:13.2180,2019-03-01 05:24:08.1460,86.0,Market St at Dolores St,37.769305,-122.426826,3.0,Powell St BART Station (Market St at 4th St),37.786375,-122.404904,5905,Customer,1972.0,Male,No
3,36490,2019-02-28 17:54:26.0100,2019-03-01 04:02:36.8420,375.0,Grove St at Masonic Ave,37.774836,-122.446546,70.0,Central Ave at Fell St,37.773311,-122.444293,6638,Subscriber,1989.0,Other,No
4,1585,2019-02-28 23:54:18.5490,2019-03-01 00:20:44.0740,7.0,Frank H Ogawa Plaza,37.804562,-122.271738,222.0,10th Ave at E 15th St,37.792714,-122.248780,4898,Subscriber,1974.0,Male,Yes
5,1793,2019-02-28 23:49:58.6320,2019-03-01 00:19:51.7600,93.0,4th St at Mission Bay Blvd S,37.770407,-122.391198,323.0,Broadway at Kearny,37.798014,-122.405950,5200,Subscriber,1959.0,Male,No
6,1147,2019-02-28 23:55:35.1040,2019-03-01 00:14:42.5880,300.0,Palm St at Willow St,37.317298,-121.884995,312.0,San Jose Diridon Station,37.329732,-121.901782,3803,Subscriber,1983.0,Female,No
7,1615,2019-02-28 23:41:06.7660,2019-03-01 00:08:02.7560,10.0,Washington St at Kearny St,37.795393,-122.404770,127.0,Valencia St at 21st St,37.756708,-122.421025,6329,Subscriber,1989.0,Male,No
8,1570,2019-02-28 23:41:48.7900,2019-03-01 00:07:59.7150,10.0,Washington St at Kearny St,37.795393,-122.404770,127.0,Valencia St at 21st St,37.756708,-122.421025,6548,Subscriber,1988.0,Other,No
9,1049,2019-02-28 23:49:47.6990,2019-03-01 00:07:17.0250,19.0,Post St at Kearny St,37.788975,-122.403452,121.0,Mission Playground,37.759210,-122.421339,6488,Subscriber,1992.0,Male,No

<span style="color: blue; font-size: 30px">EDA</span>

In [15]:
# Check for null values and handle them appropriately
null_value = data.isna().sum()
null_value

duration_sec                  0
start_time                    0
end_time                      0
start_station_id            197
start_station_name          197
start_station_latitude        0
start_station_longitude       0
end_station_id              197
end_station_name            197
end_station_latitude          0
end_station_longitude         0
bike_id                       0
user_type                     0
member_birth_year          8265
member_gender              8265
bike_share_for_all_trip       0
dtype: int64

In [19]:
# Drop all null values
data = data.dropna()
data.head()

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,member_birth_year,member_gender,bike_share_for_all_trip
0,52185,2019-02-28 17:32:10.1450,2019-03-01 08:01:55.9750,21.0,Montgomery St BART Station (Market St at 2nd St),37.789625,-122.400811,13.0,Commercial St at Montgomery St,37.794231,-122.402923,4902,Customer,1984.0,Male,No
2,61854,2019-02-28 12:13:13.2180,2019-03-01 05:24:08.1460,86.0,Market St at Dolores St,37.769305,-122.426826,3.0,Powell St BART Station (Market St at 4th St),37.786375,-122.404904,5905,Customer,1972.0,Male,No
3,36490,2019-02-28 17:54:26.0100,2019-03-01 04:02:36.8420,375.0,Grove St at Masonic Ave,37.774836,-122.446546,70.0,Central Ave at Fell St,37.773311,-122.444293,6638,Subscriber,1989.0,Other,No
4,1585,2019-02-28 23:54:18.5490,2019-03-01 00:20:44.0740,7.0,Frank H Ogawa Plaza,37.804562,-122.271738,222.0,10th Ave at E 15th St,37.792714,-122.248780,4898,Subscriber,1974.0,Male,Yes
5,1793,2019-02-28 23:49:58.6320,2019-03-01 00:19:51.7600,93.0,4th St at Mission Bay Blvd S,37.770407,-122.391198,323.0,Broadway at Kearny,37.798014,-122.405950,5200,Subscriber,1959.0,Male,No

In [25]:
# Start station data
start_station_data = data[["start_station_id", "start_station_name", "start_station_latitude", "start_station_longitude"]]
start_station_data.head()

,start_station_id,start_station_name,start_station_latitude,start_station_longitude
0,21.0,Montgomery St BART Station (Market St at 2nd St),37.789625,-122.400811
2,86.0,Market St at Dolores St,37.769305,-122.426826
3,375.0,Grove St at Masonic Ave,37.774836,-122.446546
4,7.0,Frank H Ogawa Plaza,37.804562,-122.271738
5,93.0,4th St at Mission Bay Blvd S,37.770407,-122.391198

In [26]:
# Start location(latitude and longitude)
start_location = start_station_data[["start_station_latitude", "start_station_longitude"]]
start_location.head()

   start_station_latitude  start_station_longitude
0               37.789625              -122.400811
2               37.769305              -122.426826
3               37.774836              -122.446546
4               37.804562              -122.271738
5               37.770407              -122.391198

In [34]:
# Number of rides originating from each station.
num_rides = data.groupby(["start_station_id", "start_station_name", "start_station_latitude", "start_station_longitude"]).size()
num_rides.head(3)

start_station_id  start_station_name                            start_station_latitude  start_station_longitude
3.0               Powell St BART Station (Market St at 4th St)  37.786375               -122.404904                2620
4.0               Cyril Magnin St at Ellis St                   37.785881               -122.408915                 555
5.0               Powell St BART Station (Market St at 5th St)  37.783899               -122.408445                2144
dtype: int64

In [38]:
# bike share data to identify patterns and trends in usage-(most, least and average)
print("most_popular_station = {}".format(num_rides.idxmax()))
print("least_popular_station = {}".format(num_rides.idxmin()))
print("average_rides = {}".format(num_rides.mean()))

most_popular_station = (58.0, 'Market St at 10th St', 37.776619, -122.417385)
least_popular_station = (344.0, '16th St Depot', 37.766348585937386, -122.39629179239272)
average_rides = 531.7689969604863

<span style="color: blue; font-size: 30px">Data Visualization</span>

In [41]:
# Create a folium map to visualize the bike share data.
# Create a new folium map centered on the city where the bike share system is located,
# with an appropriate zoom level.
map_center = [37.776619, -122.417385] # Most popular station

fig = folium.Map(location=map_center, zoom_start=12)
fig

Assigment
Mini-Project: Analyzing and Visualizing Bike Share Data with Folium and Python
Objective:
In this mini-project, you will apply the skills learned in the previous exercises to a real-world geospatial dataset. You will analyze bike share data, visualize the locations and usage of bike share stations, and interpret the results using Folium and Python.

Dataset:
Bike Share Data (e.g., Ford GoBike Data: https://www.kaggle.com/code/chirag02/ford-gobike-data-analysis)

Tasks:
Download and preprocess the bike share data.
Download the bike share data from Kaggle (https://www.kaggle.com/code/chirag02/ford-gobike-data-analysis) and save it as a CSV file. Read the data into Python and preprocess it, if necessary, to extract information about the bike share stations, such as the station name, latitude, longitude, and the number of rides originating from each station.

Analyze the bike share data.
Using Python, analyze the bike share data to identify patterns and trends in usage. This may include calculating metrics such as the most popular stations, the least popular stations, the average number of rides per station, or any other insights you find interesting.

Create a folium map to visualize the bike share data.
Create a new folium map centered on the city where the bike share system is located, with an appropriate zoom level.

Plot the bike share station data on the map.
For each station, create a folium marker at the corresponding latitude and longitude. Customize the marker appearance based on the number of rides originating from the station (e.g., use different colors or icons for different usage ranges). Add a popup to each marker that displays the station's name and the number of rides.

Interpret the results.
Based on your analysis and visualization, draw conclusions about the bike share system. Identify any trends, patterns, or areas for improvement, and discuss how the information could be used by city planners or bike share operators to optimize the system.

Save the folium map as an HTML file.
Save the completed folium map as an HTML file so that you can easily share it with others or embed it in a web page.